### ISSUE TITLE
Any advantages over this other repo?

### ISSUE THREAD

**Issue by isaacegglestone** [rebuy-de/terraform-provider-graylog#5]
Any reason to start a new repository on this when one is already well underway on version 11?

https://github.com/suzuki-shunsuke/go-graylog/releases

**Comment by isaacegglestone** [comment]
Any update on this?

**Comment by isaacegglestone** [comment]
?

**Comment by svenwltr** [comment]
Hello @isaacegglestone,

technically we did not start a new repo while some ready solution existed. We created this repo two and a half years ago: https://github.com/rebuy-de/terraform-provider-graylog/pull/1. At this time there was no working solution for this. The repo you linked started half a year later: https://github.com/suzuki-shunsuke/go-graylog/pull/1.

We did not merge the initial PR back then, because our priorities shifted. Recently we want to continue on this, but apparently did not check good enough for existing solution.
